/**
 * Template Registry — loads pre-built templates from public/templates/
 *
 * Templates are generated by scripts/generate-templates.ts and served as
 * static HTML files. This module handles loading, caching, and discovery.
 */

export interface RegistryEntry {
  file: string;
  size: number;
}

export type Registry = Record<string, Record<string, RegistryEntry>>;

// In-memory cache for loaded templates
const templateCache = new Map<string, string>();
let registryCache: Registry | null = null;

/**
 * Load the template registry (index of all available templates).
 * Cached after first load.
 */
export async function loadRegistry(): Promise<Registry> {
  if (registryCache) return registryCache;

  try {
    const res = await fetch("/templates/registry.json");
    if (!res.ok) throw new Error(`Registry fetch failed: ${res.status}`);
    registryCache = (await res.json()) as Registry;
    return registryCache;
  } catch (err) {
    console.error("Failed to load template registry:", err);
    return {};
  }
}

/**
 * Load a single template's HTML by design system ID and section type.
 * Returns cached version if already loaded.
 */
export async function loadTemplate(
  designSystemId: string,
  sectionType: string
): Promise<string | null> {
  const cacheKey = `${designSystemId}/${sectionType}`;

  if (templateCache.has(cacheKey)) {
    return templateCache.get(cacheKey)!;
  }

  try {
    const res = await fetch(`/templates/${designSystemId}/${sectionType}.html`);
    if (!res.ok) return null;
    const html = await res.text();
    templateCache.set(cacheKey, html);
    return html;
  } catch {
    return null;
  }
}

/**
 * Get all available section types for a given design system.
 * Requires registry to be loaded first.
 */
export function getAvailableTemplates(
  registry: Registry,
  designSystemId: string
): string[] {
  const ds = registry[designSystemId];
  if (!ds) return [];
  return Object.keys(ds);
}

/**
 * Get all design system IDs that have templates in the registry.
 */
export function getAvailableDesignSystems(registry: Registry): string[] {
  return Object.keys(registry);
}

/**
 * Check if a specific template exists in the registry.
 */
export function hasTemplate(
  registry: Registry,
  designSystemId: string,
  sectionType: string
): boolean {
  return !!registry[designSystemId]?.[sectionType];
}

/**
 * Preload multiple templates in parallel (for thumbnail rendering).
 */
export async function preloadTemplates(
  designSystemId: string,
  sectionTypes: string[]
): Promise<Map<string, string>> {
  const results = new Map<string, string>();
  const promises = sectionTypes.map(async (st) => {
    const html = await loadTemplate(designSystemId, st);
    if (html) results.set(st, html);
  });
  await Promise.all(promises);
  return results;
}

/**
 * Clear the template cache (useful for dev/refresh).
 */
export function clearCache(): void {
  templateCache.clear();
  registryCache = null;
}
